baseURL = "https://rafed.github.io/devra/"
#CanonifyURLs=true

languageCode = "en-us"
theme = "ramium"

title = "DevRa"
disqusShortname = "rafed"
googleAnalytics = "UA-106132552-1"
pluralizeListTitles = false
enableemoji = false

[params]
    description = "The practical software engineering blog"
    googleSearch = "000151824860492892407:kd5zijxwj6a"
    showDate = true # make false if dont want to show date
    math = false # best to enable this in the front matter of a page
    githubProfile = "rafed"

    tagsInHome = 40
    sectionsInHome = 5
    paginatePostsPerPage = 5
    paginateTagsPerPage = 10

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "This Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Tags"
                url = "/tags/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "All Sections"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Posts"
                url = "/posts/"
                weight = 3
    
    [[menu.main]]
        name = "Author"
        url = "https://rafed.github.io/"
        weight = 3